### ISSUE TITLE
El enlace del tweet predefinido para difundir curso no es correcto

### ISSUE THREAD

**Issue by agonzalezdiez** [cecep-edu/edx-platform#5]
I just registered for TDC101 TEST de CURSO! (http://class.stanford.edu)/

**Comment by agonzalezdiez** [comment]
Lo  mismo en el mail y una concatenacion suelta:

I just registered for TDC101 TEST de CURSO+(http://class.stanford.edu)

**Comment by ovnicraft** [comment]
el errores esta en la plantilla y es un texto en ingles,  se cambio a español con el link a upex.iaen.edu.ec
